version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_built:
    commands:
      - aws s3 sync dist/github-s3-test s3://pipeline-app-test --delete